In [23]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(result)

[5 7 9]


In [27]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2 # [5, 7, 9]
print(result)

[5 7 9]


In [31]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Матричное умножение
print(result)

[[19 22]
 [43 50]]


In [35]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data) # Стандартное отклонение
print(mean)
print(std_dev)

3.0
1.4142135623730951


In [37]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2 # Быстрое поэлементное умножение
print(result)

[2 4 6 8]


In [67]:
import numpy as np
#Теперь создадим матрицу, с которой будем работать.
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
#m[1, 0]
#m[1, :]
#m[:, 2]
#m[1, 2:]
#m[0:2, 1]
#m[0:2, 1:3]
cols = [0, 1, 3]
m[:, cols]

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

In [71]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
type(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


numpy.matrix

In [73]:
m = np.array(m)
type(m)

numpy.ndarray

In [77]:
m.shape

(3, 4)

In [80]:
m.max()

9

In [82]:
np.max(m)

9

In [84]:
m.max()

9

In [86]:
m.max(axis=1)

array([4, 8, 9])

In [88]:
m.max(axis=0)

array([9, 6, 7, 8])

In [90]:
m.mean()

4.833333333333333

In [94]:
m.mean(axis=1)

array([2.5, 6.5, 5.5])

In [96]:
m.sum()

58

In [98]:
m.sum(axis=0)

array([15,  9, 15, 19])

In [102]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])
a = True
b = 5 > 7
print(b)


False


In [104]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [106]:
pos_a = letters == 'a'
pos_a

array([ True, False, False, False,  True, False, False])

In [108]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [110]:
nums[less_then_5]

array([1, 2, 3, 4])

In [112]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [116]:
mod_m = np.logical_and(m>=3, m<=7)
mod_m


matrix([[False, False,  True,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [118]:
m[mod_m]

matrix([[3, 4, 5, 6, 7, 5, 7]])

In [120]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums[nums < 5]

array([1, 2, 3, 4])

In [122]:
nums[nums < 5] = 10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [124]:
m[m > 7] = 25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]


In [128]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [132]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [134]:
a = [[1, 2], [3, 4]]
np.matrix(a)

matrix([[1, 2],
        [3, 4]])

In [136]:
b = np.array([[5, 6], [7, 8]])
np.matrix(b)

matrix([[5, 6],
        [7, 8]])

In [138]:
np.matrix('[1, 2; 3, 4]')

matrix([[1, 2],
        [3, 4]])

In [140]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
np.ravel(A, order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.ravel(A, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [152]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a % 2 == 0, a * 10, a / 10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])

In [154]:
a = np.random.rand(10)
a

array([0.90408358, 0.89293498, 0.43631138, 0.40911336, 0.17324578,
       0.88980423, 0.23282399, 0.42817229, 0.12680696, 0.83741787])

In [156]:
np.where(a > 0.5, True, False)

array([ True,  True, False, False, False,  True, False, False, False,
        True])

In [158]:
np.where(a > 0.5, 1, -1)

array([ 1,  1, -1, -1, -1,  1, -1, -1, -1,  1])

In [160]:
x = np.linspace(0, 1, 5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [162]:
y = np.linspace(0, 2, 5)
y

array([0. , 0.5, 1. , 1.5, 2. ])

In [164]:
xg, yg = np.meshgrid(x, y)
xg

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [166]:
yg

array([[0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. ]])

In [168]:
import matplotlib.pyplot as plt
%matplotlib inline

In [210]:
plt.plot(xg, yg, color="r", marker="*", linestyle="none")

In [212]:
np.random.permutation(7)

array([0, 4, 6, 3, 2, 1, 5])

In [214]:
a = ['a', 'b', 'c', 'd', 'e']
np.random.permutation(a)

array(['d', 'a', 'b', 'e', 'c'], dtype='<U1')

In [216]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [218]:
arr_mix = np.random.permutation(arr)
arr_mix

array([ 2.5,  0. , 10. ,  7.5,  5. ])

In [220]:
index_mix = np.random.permutation(len(arr_mix))
index_mix

array([1, 2, 3, 4, 0])

In [222]:
arr[index_mix]

array([ 2.5,  5. ,  7.5, 10. ,  0. ])

In [224]:
v_hor_np = np.array([1, 2])
print(v_hor_np )

[1 2]


In [226]:
v_hor_zeros_v1 = np.zeros((5,))
print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0.]


In [228]:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2 )

[[0. 0. 0. 0. 0.]]


In [230]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)

[1. 1. 1. 1. 1.]


In [232]:
v_hor_one_v2 = np.ones((1, 5))
print(v_hor_one_v2)

[[1. 1. 1. 1. 1.]]


In [234]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [236]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [238]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [240]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [244]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [246]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [248]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [250]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [252]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [254]:
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [256]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [258]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [260]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [262]:
m_idnt = np.identity(3)
print(m_idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [264]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [266]:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


In [268]:
m_var = np.zeros((2, 5))
print(m_var)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [270]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [272]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [274]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [276]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [278]:
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]


In [280]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 8  4]
 [10 12]
 [12 11]]


In [282]:
print(R)

[[ 8  4]
 [10 12]
 [12 11]]


In [284]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[19 43]
 [22 50]]


In [286]:
print(R)

[[19 43]
 [22 50]]


In [288]:
 A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(f"{A_det:.9f}")
print(f"{A_T_det:.9f}")

-2.000000000
-2.000000000


In [290]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [292]:
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)

[[1 2]
 [3 4]]


In [294]:
print(R)

[[1 2]
 [3 4]]


In [300]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]
