***Задание 1. Создание и изменение массивов***

In [9]:
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

arr = arr * 2
print(arr)

arr[arr > 10] = 0
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


***Задание 2. Работа с булевыми масками***

In [29]:
import numpy as np
arr = np.random.randint(1, 101, 20)
print(arr)
deletsy_na_5 = arr[arr % 5 == 0]
print("\nЭлементы кратные 5:")
print(deletsy_na_5)
arr[arr % 5 == 0] = -1
print("\nНовый массив:")
print(arr)

[59 90 92 47 29  7 62 50 32 57 37 91 43 60 65 60 94 77 20 36]

Элементы кратные 5:
[90 50 60 65 60 20]

Новый массив:
[59 -1 92 47 29  7 62 -1 32 57 37 91 43 -1 -1 -1 94 77 -1 36]


***Задание 3. Объединение и разбиение массивов***

In [41]:
import numpy as np
arr1 = np.random.randint(0, 51, 5)
print("\nПервый массив")
print(arr1)
arr2 = np.random.randint(0, 51, 5)
print("\nВторой массив")
print(arr2)
combined = np.vstack((arr1, arr2))
print("\nОбъединенный массив:")
print(combined)
split1, split2 = np.vsplit(combined, 2)
print("\nРазделенный массив 1:")
print(split1)
print("\nРазделенный массив 2:")
print(split2)


Первый массив
[48  3 32 50 44]

Второй массив
[45 34 36 11 48]

Объединенный массив:
[[48  3 32 50 44]
 [45 34 36 11 48]]

Разделенный массив 1:
[[48  3 32 50 44]]

Разделенный массив 2:
[[45 34 36 11 48]]


***Задание 4. Генерация и работа с линейными последовательностями***

In [49]:
arr = np.linspace(-10, 10, 50)
print("\nМассив")
print(arr)
total_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])
print(f"\nОбщая сумма: {total_sum}")
print(f"\nСумма положительных элементов: {positive_sum}")
print(f"\nСумма отрицательных элементов: {negative_sum}")


Массив
[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]

Общая сумма: 7.105427357601002e-15

Сумма положительных элементов: 127.55102040816328

Сумма отрицательных элементов: -127.55102040816327


***Задание 5. Работа с диагональными и единичными матрицами***

In [53]:
identity_matrix = np.eye(4)
print("Единичная матрица 4×4:")
print(identity_matrix)
diagonal_matrix = np.diag([5, 10, 15, 20])
print("\nДиагональная матрица 4×4:")
print(diagonal_matrix)
sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)
print(f"\nСумма элементов единичной матрицы: {sum_identity}")
print(f"Сумма элементов диагональной матрицы: {sum_diagonal}")
if sum_identity > sum_diagonal:
    print("\nСумма элементов единичной матрицы больше")
elif sum_identity < sum_diagonal:
    print("\nСумма элементов диагональной матрицы больше")
else:
    print("\nСуммы элементов матриц равны")

Единичная матрица 4×4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица 4×4:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50

Сумма элементов диагональной матрицы больше


***Задание 6. Создание и базовые операции с матрицами***

In [57]:
matrix1 = np.random.randint(1, 21, (3, 3))
matrix2 = np.random.randint(1, 21, (3, 3))

print("\nМатрица 1:")
print(matrix1)
print("\nМатрица 2:")
print(matrix2)

sum1 = np.sum(matrix1)
sum2 = np.sum(matrix2)

print(f"\nСумма элементов матрицы 1: {sum1}")
print(f"Сумма элементов матрицы 2: {sum2}")



Матрица 1:
[[14  8  9]
 [15  2  2]
 [ 4 15 13]]

Матрица 2:
[[15 18  9]
 [ 6 11 11]
 [16 19 20]]

Сумма элементов матрицы 1: 82
Сумма элементов матрицы 2: 125


***Задание 7. Умножение матриц***

In [13]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 3))
print("Первая матрица (2x3):")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(3, 2))
print("\nВторая матрица (3x2):")
print(matrix2)

result = matrix1 @ matrix2
print("\nРезультат умножения матриц (2x2):")
print(result)

Первая матрица (2x3):
[[7 5 6]
 [9 1 8]]

Вторая матрица (3x2):
[[9 4]
 [1 8]
 [9 7]]

Результат умножения матриц (2x2):
[[122 110]
 [154 100]]


***Задание 8. Определитель и обратная матрица***

In [16]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))
print("Исходная матрица 3x3:")
print(matrix)

det = np.linalg.det(matrix)
print(f"\nОпределитель матрицы: {det:.2f}")

if not np.isclose(det, 0):
    inv_matrix = np.linalg.inv(matrix)
    print("\nОбратная матрица:")
    print(inv_matrix)
else:
    print("\nМатрица вырождена (определитель равен 0), обратной матрицы не существует.")

Исходная матрица 3x3:
[[ 5  6  5]
 [ 5 10  7]
 [ 8  2  9]]

Определитель матрицы: 96.00

Обратная матрица:
[[ 0.79166667 -0.45833333 -0.08333333]
 [ 0.11458333  0.05208333 -0.10416667]
 [-0.72916667  0.39583333  0.20833333]]


***Задание 9. Транспонирование и след матрицы***

In [19]:
import numpy as np

matrix = np.random.randint(1, 51, size=(4, 4))
print("Исходная матрица 4x4:")
print(matrix)

transposed_matrix = matrix.T
print("\nТранспонированная матрица:")
print(transposed_matrix)

trace = np.trace(matrix)
print(f"\nСлед матрицы (сумма диагональных элементов): {trace}")

Исходная матрица 4x4:
[[26  7 21 29]
 [ 4 40 44 50]
 [47 42 46 16]
 [39 17  6 21]]

Транспонированная матрица:
[[26  4 47 39]
 [ 7 40 42 17]
 [21 44 46  6]
 [29 50 16 21]]

След матрицы (сумма диагональных элементов): 133


***Задание 10. Системы линейных уравнений***

In [22]:
import numpy as np

A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])

B = np.array([5, 6, -2])

det_A = np.linalg.det(A)
if not np.isclose(det_A, 0):
    solution = np.linalg.solve(A, B)
    
    print("Решение системы:")
    print(f"x = {solution[0]:.2f}")
    print(f"y = {solution[1]:.2f}")
    print(f"z = {solution[2]:.2f}")
else:
    print("Система не имеет единственного решения (определитель матрицы коэффициентов равен 0)")

Решение системы:
x = 1.64
y = 0.58
z = 0.01


***Задание 11. Индивидуальное задание***

In [25]:
import numpy as np

A = np.array([
    [1, 1, 1],
    [0.6, 0.7, 0.8],
    [-2, 1, 0]
])

B = np.array([100, 72, 0])

# Метод Крамера
def cramer_solve(A, B):
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0):
        return None
    
    solutions = []
    for i in range(A.shape[1]):
        Ai = A.copy()
        Ai[:, i] = B
        det_Ai = np.linalg.det(Ai)
        solutions.append(det_Ai / det_A)
    
    return np.array(solutions)

# Матричный метод
def matrix_solve(A, B):
    try:
        A_inv = np.linalg.inv(A)
        return A_inv @ B
    except np.linalg.LinAlgError:
        return None

# Решение всеми методами
cramer_solution = cramer_solve(A, B)
matrix_solution = matrix_solve(A, B)
numpy_solution = np.linalg.solve(A, B)

# Вывод результатов
print("Решение методом Крамера:")
print(f"Металл 1: {cramer_solution[0]:.2f} кг")
print(f"Металл 2: {cramer_solution[1]:.2f} кг")
print(f"Металл 3: {cramer_solution[2]:.2f} кг")

print("\nРешение матричным методом:")
print(f"Металл 1: {matrix_solution[0]:.2f} кг")
print(f"Металл 2: {matrix_solution[1]:.2f} кг")
print(f"Металл 3: {matrix_solution[2]:.2f} кг")

print("\nРешение с помощью np.linalg.solve:")
print(f"Металл 1: {numpy_solution[0]:.2f} кг")
print(f"Металл 2: {numpy_solution[1]:.2f} кг")
print(f"Металл 3: {numpy_solution[2]:.2f} кг")

# Проверка решения
total_weight = numpy_solution.sum()
iron_content = 0.6*numpy_solution[0] + 0.7*numpy_solution[1] + 0.8*numpy_solution[2]
ratio = numpy_solution[1] / numpy_solution[0]

print("\nПроверка:")
print(f"Общий вес: {total_weight:.2f} кг (должно быть 100 кг)")
print(f"Содержание железа: {iron_content:.2f} кг (должно быть 72 кг)")
print(f"Соотношение x₂/x₁: {ratio:.2f} (должно быть 2)")

Решение методом Крамера:
Металл 1: 20.00 кг
Металл 2: 40.00 кг
Металл 3: 40.00 кг

Решение матричным методом:
Металл 1: 20.00 кг
Металл 2: 40.00 кг
Металл 3: 40.00 кг

Решение с помощью np.linalg.solve:
Металл 1: 20.00 кг
Металл 2: 40.00 кг
Металл 3: 40.00 кг

Проверка:
Общий вес: 100.00 кг (должно быть 100 кг)
Содержание железа: 72.00 кг (должно быть 72 кг)
Соотношение x₂/x₁: 2.00 (должно быть 2)
